name: osnova
description: "The app for date and organize parties with your company."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  meta: ^1.10.0
  cupertino_icons: ^1.0.2
  drift: ^2.15.0
  path_provider: ^2.0.0
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.3
  go_router: ^14.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.9.0
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Classic.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
