// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWnRn7hnlYxxQ_rHCk6h0uZbWB4A21N4Q',
    appId: '1:769147409146:web:0e80dcc092f1fcded46f43',
    messagingSenderId: '769147409146',
    projectId: 'osnova-e6aa6',
    authDomain: 'osnova-e6aa6.firebaseapp.com',
    storageBucket: 'osnova-e6aa6.appspot.com',
    measurementId: 'G-0GHT5M8WNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmAeDCKQIGgrbiTSlXw6BApRbGyyJ8kjI',
    appId: '1:769147409146:android:5cf7145f1bfde650d46f43',
    messagingSenderId: '769147409146',
    projectId: 'osnova-e6aa6',
    storageBucket: 'osnova-e6aa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACCHVV1LgkxJ-DrZnynWkxQrS619G6ewA',
    appId: '1:769147409146:ios:a0aa517bf46e50a2d46f43',
    messagingSenderId: '769147409146',
    projectId: 'osnova-e6aa6',
    storageBucket: 'osnova-e6aa6.appspot.com',
    iosBundleId: 'com.example.osnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACCHVV1LgkxJ-DrZnynWkxQrS619G6ewA',
    appId: '1:769147409146:ios:a0aa517bf46e50a2d46f43',
    messagingSenderId: '769147409146',
    projectId: 'osnova-e6aa6',
    storageBucket: 'osnova-e6aa6.appspot.com',
    iosBundleId: 'com.example.osnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWnRn7hnlYxxQ_rHCk6h0uZbWB4A21N4Q',
    appId: '1:769147409146:web:de02475cc73f826fd46f43',
    messagingSenderId: '769147409146',
    projectId: 'osnova-e6aa6',
    authDomain: 'osnova-e6aa6.firebaseapp.com',
    storageBucket: 'osnova-e6aa6.appspot.com',
    measurementId: 'G-FFTCG40X60',
  );
}
